# Site settings
title: Walsh Materials Design Group
email: a.walsh[at]imperial.ac.uk 
description: Computational Materials Science 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wmd-group.github.io" # the base hostname & protocol for your site
twitter_username: lonepair
github_username:  WMD-group 

# Flowery
permalink: pretty
# paginate: 3

# Build settings
markdown: kramdown
